name: Convert an inventory to CycloneDx
description: Composite action which converts an inventory to a cyclonedx document.

inputs:
  inventory-input:
    description: The input inventory file path which to convert.
    required: true
  cyclonedx-output:
    description: The output cyclonedx bom file path.
    required: true

outputs:
  bom:
    description: The resulting cyclonedx file path.
    value: ${{ steps.set-output.outputs.bom }}

runs:
  using: "composite"
  steps:
    # Runs the conversion process via the correct maven plugin.
    - name: convert-inventory-to-cyclonedx
      shell: bash
      run: |
        mvn -f convert_inventory-to-cyclonedx.xml process-resources \
        -Dinput=${{ inputs.inventory-input }} -Doutput=${{ inputs.cyclonedx-output }}
      working-directory: processors

    # Provides the converted inventory path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        output_clean="${{ inputs.cyclonedx-output }}"
        output_clean="${output_clean#../}"
        echo "bom=${output_clean}" >> "$GITHUB_OUTPUT"