name: Convert SPDX To Inventory
description: Composite action which converts a SPDX document into an inventory.

inputs:
  spdx-input:
    description: The spdx bom file path.
    required: true
  inventory-output:
    description: The converted inventory file path.
    required: true

outputs:
  converted-inventory:
    description: The converted inventory file path.
    value: ${{ steps.set-output.outputs.converted-inventory }}

runs:
  using: "composite"
  steps:
    # Runs the conversion process via the correct maven plugin.
    - name: convert-spdx-to-inventory
      shell: bash
      run: |
        mvn -f convert_spdx-to-inventory.xml process-resources -Dinput=${{ inputs.spdx-input }} -Doutput=${{ inputs.inventory-output }}
      working-directory: processors

    # Provides the converted inventory path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.inventory-output }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "converted-inventory=${inventory_output_clean}" >> "$GITHUB_OUTPUT"