name: Resolve artifacts
description: A composite action which resolves artifacts for additional information.

inputs:
  input-inventory:
    description: "The inventory from which to extract the artifacts to resolve."
    required: true
  output-inventory:
    description: "The inventory file in which to save the resolved artifacts."
    required: true

outputs:
  output-inventory:
    description: The repository path of the resolved inventory.
    value: ${{ steps.set-output.outputs.resolved-inventory }}

runs:
  using: composite
  steps:
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/resolved
        key: maven-index-${{ env.date }}

    - name: Unpack index
      if: steps.restore-cache.outputs.cache-hit == true
      shell: bash
      run: |
        unzip /tmp/resolved/maven-index.zip

    - name: Scan
      shell: bash
      run: |
        mvn -f resolved_inventory-resolver.xml process-resources \
        -DinputFile=${{ inputs.input-inventory }} \
        -DoutputFile=${{ inputs.output-inventory }}
      working-directory: processors

    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "resolved-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT

    - name: Pack index
      shell: bash
      run: |
        zip -r /tmp/resolved/maven-index.zip /tmp/resolved/download

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: /tmp/resolved