name: Pick container image
description: Download the right container image and provides information about the image as outputs.

inputs:
  image:
    required: true
    description: The name of the image, corresponding to the top level directories in this repo.

outputs:
  image-registry:
    description: The image registry
    value: ${{ steps.pick-container.outputs.image-registry }}
      
  image-repo:
    description: The image repository
    value: ${{ steps.pick-container.outputs.image-repo }}
      
  image-tag:
    description: The image tag
    value: ${{ steps.pick-container.outputs.image-tag }}

runs:
  using: composite
  steps:
    - name: Pick container
      id: pick-container
      shell: bash
      run: |
        if [ "${{ inputs.image }}" == "keycloak-25.0.4" ]; then
          echo "image-registry=keycloak" >> $GITHUB_OUTPUT
          echo "image-repo=keycloak" >> $GITHUB_OUTPUT
          echo "image-tag=25.0.4" >> $GITHUB_OUTPUT
          docker pull keycloak/keycloak:25.0.4
        elif [ "${{ inputs.image }}" == "apache-httpd-2.4.62" ]; then
          echo "image-registry=docker.io" >> $GITHUB_OUTPUT
          echo "image-repo=httpd" >> $GITHUB_OUTPUT
          echo "image-tag=2.4.62" >> $GITHUB_OUTPUT
          docker pull docker.io/httpd:2.4.62
        elif [ "${{ inputs.image }}" == "nginx-1.27.3" ]; then
          echo "image-registry=docker.io" >> $GITHUB_OUTPUT
          echo "image-repo=nginx" >> $GITHUB_OUTPUT
          echo "image-tag=1.27.3" >> $GITHUB_OUTPUT
          docker pull docker.io/nginx:1.27.3
        fi

        
