name: Download Vulnerability Index
description: Downloads a reduced vulnerability index from the metaeffekt-webserver.

runs:
  using: composite
  steps:
    - name: cache-index
      uses: actions/cache@v4
      with:
        path: /tmp/index.zip
        # Uses the checksum of the file to check for changes.
        key: ${{ runner.os }}-vulnerability-index-${{ hashFiles('**/index_redux.zip') }}

    - name: download-index
      shell: bash
      run: |
        if [ ! -f /tmp/index.zip ]; then
          curl -L -o /tmp/index.zip https://metaeffekt.com/security/mirror/index_redux.zip
        fi
    - name: unzip-index
      shell: bash
      run: |
        mkdir -p /tmp/.database/
        unzip /tmp/index.zip -d /tmp/.database
        echo "index-directory=/tmp/.database" >> $GITHUB_ENV
