name: Download Vulnerability Index
description: Downloads a reduced vulnerability index from the metaeffekt-webserver.

outputs:
  index-directory:
    description: The system path for the vulnerability index.
    value: /tmp/.database

runs:
  using: composite
  steps:
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/.database/index/
        key: vulnerability-index-${{ env.date }}

    - name: Download and unpack index
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p /tmp/.database
        curl -L -o /tmp/index.zip https://metaeffekt.com/security/mirror/index_redux.zip
        unzip /tmp/index.zip -d /tmp/.database

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: /tmp/.database/index/
        key: vulnerability-index-${{ env.date }}
