name: Run trivy
description: A composite action which creates a bom from a container image via syft.

inputs:
  image:
    description: The container image which to scan and extract
  spec:
    description: The spec which to use when creating the bom (spdx or cyclonedx)
  output-file:
    description: The path of the output file.

outputs:
  bom:
    description: The repository path of the bom.
    value: ${{ steps.syft.outputs.bom }}

runs:
  using: composite
  steps:
    - name: Run trivy
      id: trivy
      shell: bash
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y
        trivy image ${{ inputs.image }} --scanners vuln --format ${{ inputs.spec }}-json --output ${{ inputs.spec }}-json=${{ inputs.output-file }}
        echo "bom=${{ inputs.output-file }} >> $GITHUB_OUTPUT