name: Convert an inventory to Spdx
description: Composite action which converts an inventory to a spdx document.

inputs:
  inventory-input:
    description: The input inventory file path which to convert.
    required: true
  spdx-output:
    description: The spdx bom file path.
    required: true

outputs:
  bom:
    description: The spdx bom file path.
    value: ${{ steps.set-output.outputs.converted-inventory }}

runs:
  using: "composite"
  steps:
    # Runs the conversion process via the correct maven plugin.
    - name: convert-inventory-to-spdx
      shell: bash
      run: |
        mvn -f convert_inventory-to-spdx.xml process-resources \
        -Dinput=${{ inputs.inventory-input }} \
        -Doutput=${{ inputs.spdx-output }}
      working-directory: processors

    # Provides the converted inventory path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        output_clean="${{ inputs.spdx-output }}"
        output_clean="${output_clean#../}"
        echo "bom=${output_clean}" >> "$GITHUB_OUTPUT"