name: Configure container
description: Configures the container and installs needed packages if not already installed.

runs:
  using: composite
  steps:
    - name: get-maven
      shell: bash
      run: |
        sudo apt update
        if ! command -v mvn &> /dev/null; then
          echo 'Maven not installed: Installing ...'
          sudo apt install -y maven
        else
          echo 'Maven already installed: Skipping ...'
        fi

    - name: get-docker
      shell: bash
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not installed: Installing ..."
          sudo apt install -y docker
          sudo systemctl enable docker
          sudo systemctl start docker
        fi
