name: Configure container
description: Configures the container and installs needed packages if not already installed.

inputs:
  maven:
    description: True if maven should be checked/installed.
    default: 'true'
    required: false

  docker:
    description: True if docker should be checked/installed.
    default: 'true'
    required: false

runs:
  using: composite
  steps:
    - name: get-maven
      if: ${{ inputs.maven == true}}
      shell: bash
      run: |
        if ! command -v mvn &> /dev/null; then
          echo 'Maven not installed: Installing ...'
          sudo apt-get install maven
        else
          echo 'Maven already installed: Skipping ...'
        fi

    - name: get-docker
      if: ${{ inputs.docker == true}}
      shell: bash
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not installed: Installing ..."
          sudo apt-get update
          sudo apt-get install -y docker
          sudo systemctl enable docker
          sudo systemctl start docker
        fi
