name: Extract inventory from container
description: Extracts the inventory from a container.

inputs:
  image-registry:
    description: The container image registry.
    required: true

  image-repo:
    description: The container image repository.
    required: true

  image-tag:
    description: The container image tag.
    required: true

  target-dir:
    description: The target directory in which extracted information will be saved.
    required: true

  target-name:
    description: The name of the target inventory containing the container information.
    required: true

outputs:
  extracted-inventory:
    description: The path of the extracted inventory.
    value: ${{ steps.set-output.outputs.extracted-inventory }}

runs:
  using: composite
  steps:
    # Runs container extraction via the correct maven plugin.
    - name: Extract inventory
      shell: bash
      run: |
        mvn -f analyzed_extract-from-container.xml process-resources \
        -Dimage.registry=${{ inputs.image-registry }} \
        -Dimage.repo=${{ inputs.image-repo }} \
        -Dimage.tag=${{ inputs.image-tag }} \
        -DtargetInventoryDir=${{ inputs.target-dir }} \
        -DtargetInventoryPath=${{ inputs.target-name }}
      working-directory: processors

    # Provides the extracted inventory path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.target-dir }}/${{ inputs.target-name }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "extracted-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT