name: Create report
description: A composite action which creates a report containing licensing, vulnerability etc. information.

inputs:
  asset-descriptor:
    description: The asset descriptor file
    required: true

outputs:
  report:
    description: The repository path of the report.
    value: ${{ steps.set-output.outputs.enriched-inventory }}

runs:
  using: composite
  steps:
    - name: Create report
      shell: bash
      run: |
        mvn -f reported_create-vuln-report.xml process-resources \
        -DassetDescriptorFile=${{ inputs.asset-descriptor }}
      working-directory: processors

    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "enriched-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT