name: Create report
description: A composite action which creates a report containing licensing, vulnerability etc. information.

inputs:
  asset-descriptor: # More information on this can be found in the processors/resources/README.md
    description: The asset descriptor file containing all necessary parameters.
    required: true

  output-report:
    description: The output report file path.
    required: true

outputs:
  report:
    description: The file path of the final report.
    value: ${{ steps.set-output.outputs.report }}

runs:
  using: composite
  steps:
    # Runs the report generation via the correct maven plugin.
    - name: Create report
      shell: bash
      run: |
        mvn -f reported_create-vuln-report.xml process-resources \
        -DassetDescriptorFile=${{ inputs.asset-descriptor }}
      working-directory: processors

    - name: Transfer target report
      shell: bash
      run: |
        file=$(find /tmp/reported/target/ -type f -name '*.ditamap' | head -n 1)
      
        if [ -z "$file" ]; then
          exit 1
        fi
      
        mv "$file" ${{ inputs.output-report }}        

    # Provides the generated report path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "report=${inventory_output_clean}" >> $GITHUB_OUTPUT