name: Create report
description: A composite action which creates a report containing licensing, vulnerability etc. information.

inputs:
  asset-descriptor: # More information on this can be found in the processors/resources/README.md
    description: The asset descriptor file containing all necessary parameters.
    required: true

outputs:
  report:
    description: The file path of the final report.
    value: ${{ steps.set-output.outputs.enriched-inventory }}

runs:
  using: composite
  steps:
    # Runs the report generation via the correct maven plugin.
    - name: Create report
      shell: bash
      run: |
        mvn -f reported_create-vuln-report.xml process-resources \
        -DassetDescriptorFile=${{ inputs.asset-descriptor }}
      working-directory: processors

    # Provides the generated report path as an output.
    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "enriched-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT