name: Install and run syft
description: A composite action which creates a bom from a container image via syft.

inputs:
  image:
    description: The container image which to scan and extract.
  spec:
    description: The specification which to use when creating the bom (spdx or cyclonedx).
  output-file:
    description: The output file path.

outputs:
  bom:
    description: The output file path.
    value: ${{ steps.syft.outputs.bom }}

runs:
  using: composite
  steps:
    # Downloads syft, runs the install-script and calls the syft binary to extract the bom from the specified container.
    - name: Run syft
      id: syft
      shell: bash
      run: |
        curl -o /tmp/syft-install.sh https://raw.githubusercontent.com/anchore/syft/main/install.sh
        sh /tmp/syft-install.sh
        ./bin/syft ${{ inputs.image }} --output ${{ inputs.spec }}-json=${{ inputs.output-file }}
        echo "bom=${{ inputs.output-file }}" >> $GITHUB_OUTPUT
        rm -r bin