name: Enrich inventories
description: "A composite action which enriches inventories with vulnerability information."

inputs:
  input-inventory:
    description: "The input inventory."
    required: true

  input-database:
    description: "The input database used for vulnerability correlation."
    required: true

  output-inventory:
    description: "The output inventory path."
    required: true

outputs:
  inventory-path:
    description: The repository path of the enriched inventory.
    value: ${{ steps.set-output.outputs.enriched-inventory }}

runs:
  using: "composite"
  steps:
    - name: create-dashboard
      shell: bash
      run: |
        mvn -f advise_create-dashboard.xml process-resources \
        -Dinput.inventory=${{ inputs.input-inventory }} \
        -Dinput.database=${{ inputs.input-database }} \
        -Doutput.inventory=${{ inputs.output-inventory }}
        rm -r target
      working-directory: processors

    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "enriched-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT