name: Enrich inventories
description: "A composite action which enriches inventories with vulnerability information."

inputs:
  input-inventory:
    description: "The input inventory."
    required: true

  input-database:
    description: "The input database used for vulnerability correlation."
    required: true

runs:
  using: "composite"
  steps:
    - name: create-dashboard
      shell: bash
      run: |
        mvn -f advise_create-dashboard.xml process-resources \
        -Dinput.inventory=${{ inputs.input-inventory }} \
        -Dinput.database=${{ inputs.input-database }} \
        -Doutput.inventory=/tmp/enriched-inventory.xls
        echo "enriched-inventory=/tmp/enriched-inventory.xls" >> $GITHUB_ENV
        rm -r target
      working-directory: processors