name: Checkout And Configure Git
description: A composite action to checkout the repository and configure Git settings.

runs:
  using: "composite"
  steps:
    - name: configure-git
      shell: bash
      run: |
        git config --local user.name "ae-actions-runner"
        git config --local user.email "ae-actions-runner@metaeffekt.com"