name: Scan inventory
description: A composite action which scans artifacts for licenses and copyrights.

inputs:
  input-inventory:
    description: The input directory file path.
    required: true
  output-inventory:
    description: The output directory file path.
    required: true


outputs:
  scanned-inventory:
    description: The repository path of the scanned inventory.
    value: ${{ steps.set-output.outputs.scanned-inventory }}

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: |
        mvn -f scanned_inventory-scanner.xml process-resources \
        -DinputInventory=${{ inputs.input-inventory }} \
        -DtargetFile=${{ inputs.output-inventory }}
      working-directory: processors

    - name: Transfer and rename inventory
      shell: bash
      run: |
        cd /home/runner/work/metaeffekt-examples/metaeffekt-examples/processors
        source_dir="/tmp/scanned/inventories"
        destination="${{ inputs.output-inventory }}"
        file=$(find "$source_dir" -type f -name "*.xlsx" | head -n 1)
        if [ -n "$file" ]; then
          mkdir -p "$(dirname "$destination")"
          mv "$file" "$destination"
          echo "File renamed to $destination"
        else
          echo "No .xlsx file found in $source_dir"
          exit 1
        fi

    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "scanned-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT