name: Scan inventory
description: A composite action which scans artifacts for licenses and copyrights.

inputs:
  input-directory:
    description: The input directory of the input inventory.
    required: true
  input-file-name:
    description: The name with extension of the input inventory.
    required: true
  output-directory:
    description: The name of the output directory.
    required: true

outputs:
  scanned-inventory:
    description: The repository path of the scanned inventory.
    value: ${{ steps.set-output.outputs.scanned-inventory }}

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: |
        mvn -f scanned_inventory-scanner.xml process-resources \
        -Dinput-dir=${{ inputs.input-directory }} \
        -Dinput-file-name=${{ inputs.input-file-name }} \
        -Doutput-dir=/tmp/scanned/inventories
      working-directory: processors

    - name: Transfer and rename inventory
      shell: bash
      run: |
        source_dir="/tmp/scanned/inventories"
        destination="${{ inputs.output-directory }}"
        file=$(find "$source_dir" -type f -name "*.xlsx" | head -n 1)
        if [ -n "$file" ]; then
          mkdir -p "$(dirname "$destination")"
          mv "$file" "$destination"
          echo "File renamed to $destination"
        else
          echo "No .xlsx file found in $source_dir"
          exit 1
        fi

    - name: Set output
      id: set-output
      shell: bash
      run: |
        inventory_output_clean="${{ inputs.output-inventory }}"
        inventory_output_clean="${inventory_output_clean#../}"
        echo "scanned-inventory=${inventory_output_clean}" >> $GITHUB_OUTPUT