name: Process File
description: Processes a file path into the target file path, without the file ending.

inputs:
  file-path:
    description: The input file path.
    required: true

outputs:
  asset-name:
    description: The asset name contained in the path.
    value: ${{ env.asset-name }}

runs:
  using: composite
  steps:
    - name: Set up environment variables
      shell: bash
      run: |
        INPUT_PATH="${{ inputs.file-path }}"
        ASSET_NAME=$(echo "$INPUT_PATH" | cut -d'/' -f1)
        echo "asset-name=$ASSET_NAME" >> $GITHUB_ENV