name: Checkout And Configure Git
description: A composite action to checkout the repository and configure Git settings.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - shell: bash
      run: |
        git config --local user.name "ae-actions-runner"
        git config --local user.email "ae-actions-runner@metaeffekt.com"
        git add .
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Automated commit from actions runner"
          git push
        fi