name: Repository Cascade [Caller]

on:
  workflow_dispatch:

jobs:
  generate-boms:
    strategy:
      matrix:
        bom: [
          example-0.1.0/01-analyzed/example-0.1.0-analyzed.xls,
          keycloak-25.0.4/01-analyzed/keycloak-25.0.4-analyzed.xls,
          keycloak-cli-25.0.2/01-analyzed/keycloak-cli-25.0.2-analyzed.xls,
          openssl-1.1.1i/01-analyzed/openssl-1.1.1o-analyzed.xls,
          openssl-3.0.6/01-analyzed/openssl-3.0.6-analyzed.xls]
    runs-on: ubuntu-latest

    steps:
      - name: Generate CycloneDx BOMs
        uses: ./.github/workflows/analyzed_inventory-to-cyclonedx.yml
        with:
          inventory: ${{ matrix.bom }}

      - name: Generate SPDX BOMs
        uses: ./.github/workflows/analyzed_inventory-to-spdx.yml
        with:
          inventory: ${{ matrix.bom }}
