name: Generate Sbomqs Score
run-name: Generate Sbomqs Score
on:
  workflow_dispatch:

jobs:
  sbomqs-score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install sbomqs
        run: |
          mkdir -p /opt/sbomqs
          curl -L -o /opt/sbomqs/sbomqs.deb https://github.com/interlynk-io/sbomqs/releases/download/v0.2.0/sbomqs_0.2.0_amd64.deb
          sudo dpkg -i /tmp/sbomqs/ sbomqs.deb

      # This takes all .json files in the repository and runs them through sbomqs, as for now we only have boms as .json.
      - name: Run sbomqs score
        run: |
          find . -type f -name "*.json" | while read json_file; do
            output_file="${json_file%.json}.sbomqs.txt"
            sbomqs score "$json_file" > "$output_file"
          done

      - uses: ./.github/actions/configure/git # Configures git and pushes changes.


