name: Generate Sbomqs Score
run-name: Generate Sbomqs Score
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  sbomqs-score:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v3

      - name: checkout-new-branch
        run: |
          git checkout -b ae-runner-sbomqs
          git pull origin main

      - name: install-sbomqs
        run: |
          wget https://github.com/interlynk-io/sbomqs/releases/download/v0.2.0/sbomqs_0.2.0_amd64.deb -O sbomqs.deb
          sudo dpkg -i sbomqs.deb

      - name: run-sbomqs-score
        run: |
          find . -type f -name "*.json" | while read json_file; do
            output_file="${json_file%.json}-sbomqs.txt"
            sbomqs score "$json_file" > "$output_file"
          done

      - name: commit-sbomqs-files
        run: |
          git config --local user.name "ae-actions-runner"
          git config --local user.email "ae-actions-runner@metaeffekt.com"
          git add *.txt
          git commit -m "Actions runner added sbomqs scores."
          git push --set-upstream origin ae-runner-sbomqs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

