name: Resolve artifacts

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: "The inventory from which to extract the artifacts to resolve."
        required: true
        default: keycloak-25.0.4/01-analyzed/keycloak-25.0.4-analyzed.xlsx


  workflow_call:
    inputs:
      inventory:
        description: "The inventory from which to extract the artifacts to resolve."
        required: true
        type: string

    outputs:
      resolved-inventory:
        value: ${{ jobs.resolve-artifacts.outputs.resolved-inventory }}

jobs:
  resolve-artifacts:
    runs-on: ubuntu-latest
    outputs:
      resolved-inventory: ${{ steps.resolve.outputs.resolved-inventory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './processors/processor-parent.xml'

      - name: Configure runner
        uses: ./.github/actions/util/configure-runner
        with:
          maven: true

      - name: Extract file name
        id: process-input
        uses: ./.github/actions/util/extract-file-name
        with:
          file-path: ${{ inputs.inventory }}

      - name: Resolve artifacts
        id: resolve
        uses: ./.github/actions/resolved/resolve-artifacts
        with:
          input-inventory: ../${{ inputs.inventory }}
          output-inventory: ../${{ steps.process-input.outputs.asset-name }}/02-resolved/${{ steps.process-input.outputs.asset-name }}-resolved.xls

      - uses: ./.github/actions/util/push-to-repository # Configures git and pushes changes.
