name: Scan inventory

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: "The inventory file path path."
        required: true
        default: keycloak-25.0.4/03-advised/keycloak-25.0.4-advised.xls

  workflow_call:
    inputs:
      inventory:
        description: "The inventory file path."
        required: true
        type: string


    outputs:
      scanned-inventory:
        value: ${{ jobs.scan-inventory.outputs.scanned-inventory }}

jobs:
  scan-inventory:
    runs-on: ubuntu-latest
    outputs:
      scanned-inventory: ${{ steps.scan.outputs.scanned-inventory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './processors/processor-parent.xml'

      - name: Configure runner
        uses: ./.github/actions/util/configure-runner
        with:
          maven: true

      - name: Extract file name
        id: process-input
        uses: ./.github/actions/util/extract-file-name
        with:
          file-path: ${{ inputs.inventory }}

      - name: Scan inventory
        id: scan
        uses: ./.github/actions/scanned/scan-inventory
        with:
          inputInventory: ../${{ inputs.inventory }}
          targetFile: ../${{ steps.process-input.outputs.asset-name }}/04-scanned/${{ steps.process-input.outputs.asset-name }}-scanned.xls

      - uses: ./.github/actions/util/push-to-repository # Configures git and pushes changes.
