name: Convert SPDX to inventory

on:
  workflow_dispatch:
    inputs:
      spdx:
        description: "The SPDX-Bom file path."
        required: true
        default: keycloak-25.0.4/01-analyzed/keycloak-25.0.4-spdx-2.3_exporter_new.json

  workflow_call:
    inputs:
      spdx:
        description: "The SPDX-Bom file path."
        required: true
        type: string

    outputs:
      converted-inventory:
        value: ${{ jobs.spdx-to-inventory.outputs.converted-inventory }}

jobs:
  spdx-to-inventory:
    runs-on: ubuntu-latest
    outputs:
      converted-inventory: ${{ steps.convert.outputs.converted-inventory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './processors/processor-parent.xml'

      - name: Configure runner
        uses: ./.github/actions/util/configure-runner
        with:
          maven: true

      - name: Extract file name
        id: process-input
        uses: ./.github/actions/util/extract-file-name
        with:
          file-path: ${{ inputs.spdx }}

      - name: Convert SPDX to inventory
        id: convert
        uses: ./.github/actions/analyzed/spdx-to-inventory
        with:
          spdx-input: ../${{ inputs.spdx }}
          inventory-output: ../${{ steps.process-input.outputs.asset-name }}/01-analyzed/${{ steps.process-input.outputs.asset-name }}-imported.xls

      - uses: ./.github/actions/util/push-to-repository # Configures git and pushes changes.
