name: Single Full Cascade [Caller]

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: "The inventory file location, relative to the processors directory."
        required: true
        default: keycloak-25.0.4/01-analyzed/keycloak-25.0.4-analyzed.xls

  workflow_call:
    inputs:
      inventory:
        description: "The inventory file location, relative to the processors directory."
        required: true
        type: string

jobs:
  inventory-to-spdx:
    uses: ./.github/workflows/analyzed_inventory-to-spdx.yml
    with:
      inventory: ${{ inputs.inventory }}

  inventory-to-cyclonedx:
    uses: ./.github/workflows/analyzed_inventory-to-cyclonedx.yml
    with:
      inventory: ${{ inputs.inventory }}

  resolve-inventory:
    uses: ./.github/workflows/resolved_resolve-artifacts.yml
    needs: inventory-to-cyclonedx
    with:
      inventory: ${{ needs.inventory-to-cyclonedx.outputs.bom }}

  enrich-inventory:
    needs: resolve-inventory
    uses: ./.github/workflows/advised_enrich-inventory.yml
    with:
      converted-inventory: ${{ needs.resolve-inventory.outputs.resolved-inventory }}

  create-dashboard:
    needs: enrich-inventory
    uses: ./.github/workflows/advised_enriched-inventory-to-dashboard.yml
    with:
      enriched-inventory: ${{ needs.enrich-inventory.outputs.enriched-inventory }}

  create-report:
    needs: enrich-inventory
    uses: ./.github/workflows/reported_inventory-to-report.yml
    with:
      inventory: ${{ needs.enrich-inventory.outputs.enriched-inventory }}